services:
  v2_app:
    image: portfolio-builder-v2-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env_prod_alpaca
    volumes:
      - ./data_prod_alpaca:/app/v2/data_prod_alpaca
      - ./config:/app/v2/config:ro
