services:
  v2_app:
    image: portfolio-builder-v2-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/v2/config:ro
    networks:
      - pb_obs_net

networks:
  pb_obs_net:
    external: true
    name: pb_obs_net
