services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml:ro
    networks:
      pb_obs_net:
        aliases:
          - otelcol
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    networks:
      pb_obs_net:
        aliases:
          - alertmanager
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=730d"
      - "--storage.tsdb.retention.size=2GB"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-alerts.yml:/etc/prometheus/prometheus-alerts.yml:ro
      - prom_data:/prometheus
    depends_on:
      - otelcol
      - alertmanager
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - pb_obs_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    env_file:
      - ./.env.grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - pb_obs_net
    restart: unless-stopped

volumes:
  prom_data:
  alertmanager_data:
  grafana_data:


networks:
  pb_obs_net:
    name: pb_obs_net
