services:
  v2_app:
    env_file:
      - ./.env.live_publicdotcom_roth
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4317
      OTEL_SERVICE_NAME: portfolio-builder-v2-live_publicdotcom_roth
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=live_publicdotcom_roth
    command: [ "python", "run_app.py", "--config", "configs/app_live_publicdotcom_roth.yml" ]
    volumes:
      - ./data_live_publicdotcom_roth:/app/v2/data_live_publicdotcom_roth
    restart: unless-stopped
