services:
  v2_app:
    image: portfolio-builder-v2-app:latest
    build:
      context: ../../ # Path to the root of the repository
      dockerfile: deployments/v2/Dockerfile
    volumes:
      - ./configs:/app/v2/configs:ro
    networks:
      - pb_obs_net

networks:
  pb_obs_net:
    external: true
    name: pb_obs_net
